### PR TITLE
Update PrivateRoute.tsx

### PR DESCRIPTION
**Pull request by tinashechiraya**
this is linked to issue:
https://github.com/kartoza/africa_rangeland_watch/issues/86

[Screencast from 2024-11-22 12-08-18.webm](https://github.com/user-attachments/assets/5edf8445-43ee-429d-bd68-23dbaf683a66)

### CODE REVIEW

**Comment by dimasciput** [comment]
@tinashechiraya what happens if you in about page, click login, and then cancel the login modal? It should be still in the about page right?

**Comment by tinashechiraya** [comment]
@dimasciput currently if you cancel it returns to the home page but let me patch it so it stays on current page

**Comment by tinashechiraya** [comment]
@dimasciput resolved

**Comment by dimasciput** [comment]
@tinashechiraya think it’s a bit weird to show a blank screen and a login modal when a user opens a private url. Maybe it’s better to just redirect them to the home page, show the login modal there, and add a url parameter like `next=/map`. Just like how Django handles it when you try to access the admin page without being logged in.

For the about page, let’s keep it simple. We don’t need to create a session for every public page. If the login modal is opened from a public page, it should just close the modal when user clicks cancel.

**Comment by tinashechiraya** [comment]
@dimasciput okay will update this pr

**Comment by tinashechiraya** [comment]
[Screencast from 2024-11-26 11-43-44.webm](https://github.com/user-attachments/assets/b85a10ce-00a0-4c99-a29e-ba4e8d5c6265)


resolved @dimasciput

**Review by dimasciput — APPROVED** [review]

**Pull request merged**
