### PR TITLE
Implement organisation on boarding (onboarding 3)

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 2024-11-22 14-23-44.webm](https://github.com/user-attachments/assets/64ceb1ad-e911-471c-aceb-6557ce9d05b9)

- [x] fetching organization members
- [x] adding people (sending invites with designed email template)
- [x] fetching invitations for organizations
- [x] searching for members
- [x] deleting members from an organization
- [x] add tests
- [x] show add , delete and invitations when manager only
- [x] register user first if not registered then accept invite and join organisation

this is linked to issue:
https://github.com/kartoza/africa_rangeland_watch/issues/101

### CODE REVIEW

**Comment by amyburness** [comment]
@tinashechiraya how is this feature progressing?

**Comment by tinashechiraya** [comment]
Hi @amyburness ,almost ready for review

**Comment by tinashechiraya** [comment]
[Screencast from 2024-11-22 12-07-25.webm](https://github.com/user-attachments/assets/a8553e92-eab9-49e1-ba27-44a3691fda4c)

**Comment by tinashechiraya** [comment]
[Screencast from 2024-11-14 16-44-54.webm](https://github.com/user-attachments/assets/aa21434b-9631-4901-9fe5-39a69271da43)
[Screencast from 2024-11-22 13-31-32.webm](https://github.com/user-attachments/assets/f77b46ab-f074-4000-a6f1-be38a289a361)
[Screencast from 2024-11-22 13-39-30.webm](https://github.com/user-attachments/assets/3f0c7027-0511-41d7-b47f-d3f1de917b16)

**Review by dimasciput — CHANGES_REQUESTED** [review]

**Review by dimasciput — APPROVED** [review]

**Pull request merged**
